/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskSplatRouteImport } from './routes/_desk/$'
import { Route as DeskCombinationsRouteImport } from './routes/_desk/combinations'
import { Route as DeskConnectionsRouteImport } from './routes/_desk/connections'
import { Route as DeskEngineRouteImport } from './routes/_desk/engine'
import { Route as DeskHeatmapRouteImport } from './routes/_desk/heatmap'
import { Route as DeskLanesRouteImport } from './routes/_desk/lanes'
import { Route as DeskOrdersRouteImport } from './routes/_desk/orders'
import { Route as DeskPerformanceRouteImport } from './routes/_desk/performance'
import { Route as DeskPositionsRouteImport } from './routes/_desk/positions'
import { Route as DeskReplayRouteImport } from './routes/_desk/replay'
import { Route as DeskResultsRouteImport } from './routes/_desk/results'
import { Route as DeskSettingsRouteImport } from './routes/_desk/settings'
import { Route as DeskStatisticsRouteImport } from './routes/_desk/statistics'
import { Route as DeskStrategiesRouteImport } from './routes/_desk/strategies'
import { Route as DeskSystemRouteImport } from './routes/_desk/system'
import { Route as DeskTacticsRouteImport } from './routes/_desk/tactics'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSplatRoute = DeskSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCombinationsRoute = DeskCombinationsRouteImport.update({
  id: '/combinations',
  path: '/combinations',
  getParentRoute: () => DeskRoute,
} as any)
const DeskConnectionsRoute = DeskConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DeskRoute,
} as any)
const DeskEngineRoute = DeskEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => DeskRoute,
} as any)
const DeskHeatmapRoute = DeskHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLanesRoute = DeskLanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOrdersRoute = DeskOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPerformanceRoute = DeskPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPositionsRoute = DeskPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReplayRoute = DeskReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => DeskRoute,
} as any)
const DeskResultsRoute = DeskResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskStatisticsRoute = DeskStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DeskRoute,
} as any)
const DeskStrategiesRoute = DeskStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSystemRoute = DeskSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTacticsRoute = DeskTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/$': typeof DeskSplatRoute
  '/combinations': typeof DeskCombinationsRoute
  '/connections': typeof DeskConnectionsRoute
  '/engine': typeof DeskEngineRoute
  '/heatmap': typeof DeskHeatmapRoute
  '/lanes': typeof DeskLanesRoute
  '/orders': typeof DeskOrdersRoute
  '/performance': typeof DeskPerformanceRoute
  '/positions': typeof DeskPositionsRoute
  '/replay': typeof DeskReplayRoute
  '/results': typeof DeskResultsRoute
  '/settings': typeof DeskSettingsRoute
  '/statistics': typeof DeskStatisticsRoute
  '/strategies': typeof DeskStrategiesRoute
  '/system': typeof DeskSystemRoute
  '/tactics': typeof DeskTacticsRoute
}
export interface FileRoutesByTo {
  '/$': typeof DeskSplatRoute
  '/combinations': typeof DeskCombinationsRoute
  '/connections': typeof DeskConnectionsRoute
  '/engine': typeof DeskEngineRoute
  '/heatmap': typeof DeskHeatmapRoute
  '/lanes': typeof DeskLanesRoute
  '/orders': typeof DeskOrdersRoute
  '/performance': typeof DeskPerformanceRoute
  '/positions': typeof DeskPositionsRoute
  '/replay': typeof DeskReplayRoute
  '/results': typeof DeskResultsRoute
  '/settings': typeof DeskSettingsRoute
  '/statistics': typeof DeskStatisticsRoute
  '/strategies': typeof DeskStrategiesRoute
  '/system': typeof DeskSystemRoute
  '/tactics': typeof DeskTacticsRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/_desk/$': typeof DeskSplatRoute
  '/_desk/combinations': typeof DeskCombinationsRoute
  '/_desk/connections': typeof DeskConnectionsRoute
  '/_desk/engine': typeof DeskEngineRoute
  '/_desk/heatmap': typeof DeskHeatmapRoute
  '/_desk/lanes': typeof DeskLanesRoute
  '/_desk/orders': typeof DeskOrdersRoute
  '/_desk/performance': typeof DeskPerformanceRoute
  '/_desk/positions': typeof DeskPositionsRoute
  '/_desk/replay': typeof DeskReplayRoute
  '/_desk/results': typeof DeskResultsRoute
  '/_desk/settings': typeof DeskSettingsRoute
  '/_desk/statistics': typeof DeskStatisticsRoute
  '/_desk/strategies': typeof DeskStrategiesRoute
  '/_desk/system': typeof DeskSystemRoute
  '/_desk/tactics': typeof DeskTacticsRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/combinations'
    | '/connections'
    | '/engine'
    | '/heatmap'
    | '/lanes'
    | '/orders'
    | '/performance'
    | '/positions'
    | '/replay'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/strategies'
    | '/system'
    | '/tactics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/combinations'
    | '/connections'
    | '/engine'
    | '/heatmap'
    | '/lanes'
    | '/orders'
    | '/performance'
    | '/positions'
    | '/replay'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/strategies'
    | '/system'
    | '/tactics'
    | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/_desk/$'
    | '/_desk/combinations'
    | '/_desk/connections'
    | '/_desk/engine'
    | '/_desk/heatmap'
    | '/_desk/lanes'
    | '/_desk/orders'
    | '/_desk/performance'
    | '/_desk/positions'
    | '/_desk/replay'
    | '/_desk/results'
    | '/_desk/settings'
    | '/_desk/statistics'
    | '/_desk/strategies'
    | '/_desk/system'
    | '/_desk/tactics'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/$': {
      id: '/_desk/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DeskSplatRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/combinations': {
      id: '/_desk/combinations'
      path: '/combinations'
      fullPath: '/combinations'
      preLoaderRoute: typeof DeskCombinationsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/connections': {
      id: '/_desk/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DeskConnectionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/engine': {
      id: '/_desk/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof DeskEngineRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/heatmap': {
      id: '/_desk/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof DeskHeatmapRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/lanes': {
      id: '/_desk/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof DeskLanesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/orders': {
      id: '/_desk/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DeskOrdersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/performance': {
      id: '/_desk/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof DeskPerformanceRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/positions': {
      id: '/_desk/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof DeskPositionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/replay': {
      id: '/_desk/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof DeskReplayRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/results': {
      id: '/_desk/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof DeskResultsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/settings': {
      id: '/_desk/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/statistics': {
      id: '/_desk/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof DeskStatisticsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/strategies': {
      id: '/_desk/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof DeskStrategiesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/system': {
      id: '/_desk/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DeskSystemRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/tactics': {
      id: '/_desk/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof DeskTacticsRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskSplatRoute: typeof DeskSplatRoute
  DeskCombinationsRoute: typeof DeskCombinationsRoute
  DeskConnectionsRoute: typeof DeskConnectionsRoute
  DeskEngineRoute: typeof DeskEngineRoute
  DeskHeatmapRoute: typeof DeskHeatmapRoute
  DeskLanesRoute: typeof DeskLanesRoute
  DeskOrdersRoute: typeof DeskOrdersRoute
  DeskPerformanceRoute: typeof DeskPerformanceRoute
  DeskPositionsRoute: typeof DeskPositionsRoute
  DeskReplayRoute: typeof DeskReplayRoute
  DeskResultsRoute: typeof DeskResultsRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskStatisticsRoute: typeof DeskStatisticsRoute
  DeskStrategiesRoute: typeof DeskStrategiesRoute
  DeskSystemRoute: typeof DeskSystemRoute
  DeskTacticsRoute: typeof DeskTacticsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskSplatRoute: DeskSplatRoute,
  DeskCombinationsRoute: DeskCombinationsRoute,
  DeskConnectionsRoute: DeskConnectionsRoute,
  DeskEngineRoute: DeskEngineRoute,
  DeskHeatmapRoute: DeskHeatmapRoute,
  DeskLanesRoute: DeskLanesRoute,
  DeskOrdersRoute: DeskOrdersRoute,
  DeskPerformanceRoute: DeskPerformanceRoute,
  DeskPositionsRoute: DeskPositionsRoute,
  DeskReplayRoute: DeskReplayRoute,
  DeskResultsRoute: DeskResultsRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskStatisticsRoute: DeskStatisticsRoute,
  DeskStrategiesRoute: DeskStrategiesRoute,
  DeskSystemRoute: DeskSystemRoute,
  DeskTacticsRoute: DeskTacticsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
