import { DEFAULT_BLOCK_CONFIG, DEFAULT_TACTIC_CONFIG, DEFAULT_THRESHOLDS, DEFAULT_STRATEGY_TOGGLES, DEFAULT_ENABLED_KINDS, DEFAULT_INTERVAL_STRATEGY, DEFAULT_LAST_N_PROGRESS, DEFAULT_SHORT_PROGRESS, LIVE_BLOCK_COUNTS, LIVE_ENABLED_KINDS, X01_DEFAULTS } from "./engine.ts";
import { BOT_TYPES, defaultBotConfig, defaultBotsPersist } from "./bots.ts";
import type { DeskSettingsSnap } from "./settings-sync.ts";

export interface SettingsPreset {
  id: string;
  label: string;
  blurb: string;
  builtin: boolean;
  patch: Partial<DeskSettingsSnap>;
  /** Measured tape. Positions are unique symbol+side. Orders count each partial on its own. */
  info?: PresetTapeInfo;
}

export interface PresetTapeInfo {
  winHoursPct: number;
  pf: number;
  ddt: number;
  tradesPerHour: number;
  positions: number;
  orders: number;
}

const LIVE_CFG = {
  ...DEFAULT_TACTIC_CONFIG,
  trailingPct: 1.5,
  slAtr: 0.9,
  tpRatio: 1.6,
  dcaCount: 1,
  maxHoldBars: 8,
  maxHoldTicks: 20000,
};

const BLOCK_LIVE = {
  ...DEFAULT_BLOCK_CONFIG,
  counts: [...LIVE_BLOCK_COUNTS],
  maxMultiple: 6,
  evalPosCount: 6,
  evalLastNs: [1, 2, 3, 4, 5, 6],
  volumeMode: "parallel" as const,
  overallMode: "parallel" as const,
  sides: "both" as const,
  volumeRatio: 0.2,
  overallVolumeRatio: 1.5,
  sharedVolumeRatio: 1.5,
  pauseCountRatio: 1,
  keepAdjusted: true,
  maxVolumeMultiplier: 2.5,
};

export const BUILTIN_PRESETS: SettingsPreset[] = [
  {
    id: "x01-live",
    label: "x01 live",
    blurb: "Mainnet · 120 symbols · trail 1.5 · Block 1–6 · PF 1.35",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      symbolCount: 120,
      tactic: "trailing",
      rangeType: "geometric",
      tacticConfig: { ...LIVE_CFG },
      blockConfig: { ...BLOCK_LIVE, minRelPf: X01_DEFAULTS.minPf },
      intervalStrategy: { ...DEFAULT_INTERVAL_STRATEGY },
      lastNProgress: { ...DEFAULT_LAST_N_PROGRESS, evalNs: [...DEFAULT_LAST_N_PROGRESS.evalNs], validNs: [...DEFAULT_LAST_N_PROGRESS.validNs], disableNs: [...DEFAULT_LAST_N_PROGRESS.disableNs] },
      thresholds: { ...DEFAULT_THRESHOLDS, minPf: X01_DEFAULTS.minPf },
      liveTape: true,
      hedgeMode: true,
      marginMode: "cross",
      useMaxLeverage: true,
      leverage: 0,
      sessionPhase: "running",
      comboOnlyPositive: true,
    },
  },
  {
    id: "vst-paper",
    label: "VST paper",
    blurb: "Demo VST-02 · hybrid / geometric · 120 symbols",
    builtin: true,
    patch: {
      activeConnId: "bingx-vst-02",
      symbolCount: 120,
      tactic: "hybrid",
      rangeType: "geometric",
      tacticConfig: { ...LIVE_CFG },
      blockConfig: { ...BLOCK_LIVE },
      intervalStrategy: { ...DEFAULT_INTERVAL_STRATEGY },
      lastNProgress: { ...DEFAULT_LAST_N_PROGRESS, evalNs: [...DEFAULT_LAST_N_PROGRESS.evalNs], validNs: [...DEFAULT_LAST_N_PROGRESS.validNs], disableNs: [...DEFAULT_LAST_N_PROGRESS.disableNs] },
      liveTape: true,
      sessionPhase: "running",
    },
  },
  {
    id: "strict-pf",
    label: "Strict PF",
    blurb: "Min PF 2.0 · last-N 12 disable at 2.0 · Block 1–3",
    builtin: true,
    patch: {
      tactic: "trailing",
      rangeType: "geometric",
      tacticConfig: { ...LIVE_CFG },
      thresholds: { ...DEFAULT_THRESHOLDS, minPf: 2 },
      blockConfig: {
        ...BLOCK_LIVE,
        counts: [1, 2, 3],
        evalLastNs: [1, 2, 3],
        maxMultiple: 3,
        minRelPf: 2,
        liveDisableMinPf: 2,
      },
      lastN: 12,
    },
  },
  {
    id: "conservative",
    label: "Conservative",
    blurb: "25 symbols · one side · Block 1–2 · higher SL",
    builtin: true,
    patch: {
      symbolCount: 25,
      tactic: "trailing",
      rangeType: "geometric",
      tacticConfig: { ...LIVE_CFG, slAtr: 1.1, tpRatio: 1.6, trailingPct: 1.5 },
      blockConfig: { ...BLOCK_LIVE, counts: [1, 2], maxMultiple: 2, evalLastNs: [1, 2, 3], sides: "one" },
      thresholds: { ...DEFAULT_THRESHOLDS, minPf: X01_DEFAULTS.minPf },
    },
  },
  {
    id: "block-core",
    label: "Block 1–3",
    blurb: "Only proven Block windows · stack + windows · parallel",
    builtin: true,
    patch: {
      blockConfig: {
        ...BLOCK_LIVE,
        counts: [1, 2, 3],
        maxMultiple: 3,
        evalLastNs: [1, 2, 3],
        evalPosCount: 6,
      },
    },
  },
  {
    id: "short-block-live",
    label: "Short + Block",
    blurb: "x01 · 120 · indications only · short TP/SL · Block Active 1-step · min PF 1.8",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      symbolCount: 120,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      tacticConfig: {
        ...LIVE_CFG,
        shortRange: true,
        tpAtr: 0.48,
        slOfTp: 0.75,
        slAtr: 0.36,
        tpRatio: 4 / 3,
        axisLevels: 5,
        maxHoldBars: 8,
        maxHoldTicks: 16,
      },
      blockConfig: {
        ...BLOCK_LIVE,
        counts: [1],
        maxMultiple: 1,
        minMultiple: 1,
        evalLastNs: [1],
        evalPosCount: 1,
        minActiveLevel: 1,
        activeLive: true,
        relAdditive: true,
        relVolumeRatio: 0.2,
        minRelPf: 1.8,
        liveLastN: 12,
        liveDisable: true,
        liveDisableMinPf: 1.8,
        liveDisableMinSamples: 4,
        symbolEvalHours: 100,
        hourCoord: true,
        autoEval: true,
      },
      thresholds: { ...DEFAULT_THRESHOLDS, minPf: 1.8, maxMdd: 0.12, minWr: 0.55, minVf: 1.12, maxDdt: 18 },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
      liveTape: true,
      comboOnlyPositive: true,
      comboTactic: "all",
      comboRange: "all",
      evalHours: [4, 8, 16],
      evalLastNs: [12, 15, 50],
      lastN: 12,
      lastNs: { picks: 12, lanes: 12, last: 12, ongoing: 12, next: 12, combos: 12 },
      lastNLinked: true,
      hedgeMode: true,
      marginMode: "cross",
      useMaxLeverage: true,
      leverage: 0,
      minSizeRatio: 1,
      sessionPhase: "running",
      strategyToggles: { ...DEFAULT_STRATEGY_TOGGLES, normal: false, trailing: true, axis: true, block: true, dca: false },
    },
  },
  {
    id: "stable-01",
    label: "Stable 01",
    blurb: "x01 live snapshot · 50 · trailing/atr · short 0.48/0.75 · Block 1–6 parallel Active · min PF 1.8",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      symbolCount: 50,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      costStep: 10,
      strategyId: "normal",
      tacticConfig: {
        trailingPct: 1.5,
        dcaCount: 1,
        dcaDrawdown: 0.8,
        axisSpacing: 0.7,
        axisLevels: 5,
        slAtr: 0.36,
        tpRatio: 4 / 3,
        tpAtr: 0.48,
        slOfTp: 0.75,
        shortRange: true,
        maxHoldBars: 8,
        maxHoldTicks: 24,
      },
      blockConfig: {
        ...BLOCK_LIVE,
        enabled: true,
        counts: [...LIVE_BLOCK_COUNTS],
        maxMultiple: 6,
        minMultiple: 1,
        addOnWin: false,
        flattenConflict: false,
        endStageOnly: false,
        cadence: 4,
        overall: true,
        volumeRatio: 0.2,
        overallVolumeRatio: 1.5,
        sharedVolumeRatio: 1.5,
        maxVolumeMultiplier: 2.5,
        pfRatio: 1.3,
        pauseCountRatio: 1,
        evalPosCount: 6,
        activeLive: true,
        minActiveLevel: 1,
        keepAdjusted: true,
        stack: true,
        windows: true,
        volumeMode: "parallel",
        overallMode: "shared",
        sides: "both",
        evalHours: 2,
        autoEval: true,
        relAdditive: true,
        relVolumeRatio: 0.2,
        minRelPf: 1.05,
        evalLastNs: [1, 2, 3, 4, 5, 6],
        liveLastN: 12,
        liveDisable: true,
        liveDisableMinPf: 1.8,
        liveDisableMinSamples: 4,
        symbolEvalHours: 100,
        hourCoord: true,
      },
      thresholds: { ...DEFAULT_THRESHOLDS, minPf: 1.8, basePf: 1.1, axisPf: 1.5, blockPf: 1.6, shortPf: 1.2, shortBasePf: 0.8, maxMdd: 0.12, minWr: 0.55, minVf: 1.12, maxDdt: 18 },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
      liveTape: true,
      comboOnlyPositive: true,
      comboTactic: "all",
      comboRange: "all",
      evalHours: [4, 8, 16],
      evalLastNs: [12, 15, 50],
      lastN: 10,
      lastNs: { picks: 10, lanes: 10, last: 10, ongoing: 10, next: 10, combos: 10 },
      lastNLinked: true,
      hedgeMode: true,
      marginMode: "cross",
      useMaxLeverage: true,
      leverage: 0,
      minSizeRatio: 1,
      sessionPhase: "running",
      strategyToggles: { normal: false, trailing: true, axis: true, block: true, dca: false },
    },
  },
  {
    id: "stable-02",
    label: "Stable 02",
    blurb: "x01 · 120 · short 0.48/0.75 · Axis full rungs · Block 1–6 0.4 · PF 1.35/1.0/1.15/1.2 · short 0.95/0.7",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      symbolCount: 120,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      costStep: 10,
      strategyId: "normal",
      tacticConfig: {
        trailingPct: 1.5,
        dcaCount: 1,
        dcaDrawdown: 0.8,
        axisSpacing: 0.7,
        axisLevels: 5,
        axisPartialRatio: 3,
        slAtr: 0.36,
        tpRatio: 4 / 3,
        tpAtr: 0.48,
        slOfTp: 0.75,
        shortRange: true,
        maxHoldBars: 8,
        maxHoldTicks: 24,
      },
      blockConfig: {
        ...BLOCK_LIVE,
        enabled: true,
        counts: [...LIVE_BLOCK_COUNTS],
        maxMultiple: 6,
        minMultiple: 1,
        addOnWin: false,
        flattenConflict: false,
        endStageOnly: false,
        cadence: 4,
        overall: true,
        volumeRatio: 0.2,
        overallVolumeRatio: 1.5,
        sharedVolumeRatio: 1.5,
        maxVolumeMultiplier: 2.5,
        pfRatio: 1.3,
        pauseCountRatio: 1,
        evalPosCount: 6,
        activeLive: true,
        minActiveLevel: 1,
        keepAdjusted: true,
        stack: true,
        windows: true,
        volumeMode: "parallel",
        overallMode: "shared",
        sides: "both",
        evalHours: 2,
        autoEval: true,
        relAdditive: true,
        relVolumeRatio: 0.2,
        minRelPf: 1.2,
        evalLastNs: [1, 2, 3, 4, 5, 6],
        liveLastN: 12,
        liveDisable: true,
        liveDisableMinPf: 1.2,
        liveDisableMinSamples: 4,
        symbolEvalHours: 100,
        hourCoord: true,
      },
      thresholds: {
        ...DEFAULT_THRESHOLDS,
        minPf: 1.35,
        basePf: 1,
        axisPf: 1.15,
        blockPf: 1.2,
        shortPf: 0.95,
        shortBasePf: 0.7,
        maxMdd: 0.12,
        minWr: 0.55,
        minVf: 1.12,
        maxDdt: 18,
      },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
      liveTape: true,
      comboOnlyPositive: true,
      comboTactic: "all",
      comboRange: "all",
      evalHours: [4, 8, 16],
      evalLastNs: [12, 15, 50],
      lastN: 10,
      lastNs: { picks: 10, lanes: 10, last: 10, ongoing: 10, next: 10, combos: 10 },
      lastNLinked: true,
      hedgeMode: true,
      marginMode: "cross",
      useMaxLeverage: true,
      leverage: 0,
      minSizeRatio: 1,
      sessionPhase: "running",
      strategyToggles: { normal: false, trailing: true, axis: true, block: true, dca: false },
    },
  },
  {
    id: "vst-working-01",
    label: "VST Working 01",
    blurb: "VST-02 · 50/300 · short 0.48/0.75 · trail 1.5 · Block 1,3–6 shared 1.5/0.2 · intern 96 · protect pinned",
    builtin: true,
    patch: {
      activeConnId: "bingx-vst-02",
      symbolCount: 50,
      evalSymbolCount: 300,
      liveSymbolCap: 50,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      costStep: 10,
      strategyId: "normal",
      tacticConfig: {
        trailingPct: 1.5,
        dcaCount: 1,
        dcaDrawdown: 0.8,
        axisSpacing: 0.7,
        axisLevels: 5,
        axisPartialRatio: 3,
        slAtr: 0.36,
        tpRatio: 4 / 3,
        tpAtr: 0.48,
        slOfTp: 0.75,
        shortRange: true,
        maxHoldBars: 3,
        maxHoldTicks: 24,
      },
      blockConfig: {
        ...BLOCK_LIVE,
        enabled: true,
        counts: [...LIVE_BLOCK_COUNTS],
        maxMultiple: 6,
        minMultiple: 1,
        addOnWin: false,
        flattenConflict: false,
        endStageOnly: false,
        cadence: 4,
        overall: true,
        overallSymbol: true,
        overallDirection: true,
        volumeRatio: 0.2,
        overallVolumeRatio: 1.5,
        sharedVolumeRatio: 1.5,
        maxVolumeMultiplier: 2.5,
        pfRatio: 1.45,
        pauseCountRatio: 0,
        evalPosCount: 6,
        activeLive: true,
        minActiveLevel: 1,
        keepAdjusted: true,
        stack: true,
        windows: true,
        volumeMode: "parallel",
        overallMode: "parallel",
        overallSharedStack: "additive",
        sides: "both",
        evalHours: 2,
        autoEval: true,
        relAdditive: true,
        relVolumeRatio: 0.2,
        minRelPf: 1.05,
        evalLastNs: [1, 2, 3, 4, 5, 6],
        liveLastN: 12,
        liveExecN: 15,
        validExecN: 15,
        liveDisable: true,
        liveDisableMinPf: 1.2,
        liveDisableMinSamples: 4,
        symbolEvalHours: 100,
        hourCoord: true,
        lastNProgress: {
          ...DEFAULT_LAST_N_PROGRESS,
          evalNs: [...DEFAULT_LAST_N_PROGRESS.evalNs],
          validNs: [...DEFAULT_LAST_N_PROGRESS.validNs],
          disableNs: [...DEFAULT_LAST_N_PROGRESS.disableNs],
        },
      },
      thresholds: {
        ...DEFAULT_THRESHOLDS,
        minPf: 0.95,
        basePf: 1,
        axisPf: 1.15,
        blockPf: 1.2,
        shortPf: 0.95,
        shortBasePf: 0.7,
        maxMdd: 0.12,
        minWr: 0.55,
        minVf: 1.12,
        maxDdt: 18,
      },
      shortProgress: {
        ...DEFAULT_SHORT_PROGRESS,
        indications: [...DEFAULT_SHORT_PROGRESS.indications],
        lastParts: [...DEFAULT_SHORT_PROGRESS.lastParts],
        activityWindows: [...DEFAULT_SHORT_PROGRESS.activityWindows],
        minTpAtr: 0.48,
        minSlOfTp: 0.75,
        maxTpAtr: 0.6,
        evalHours: 20,
        evalPositiveOnly: true,
        overallPf: 0.95,
        basePf: 0.7,
        axisPf: 0.9,
        blockPf: 1.15,
      },
      lastNProgress: {
        ...DEFAULT_LAST_N_PROGRESS,
        evalNs: [...DEFAULT_LAST_N_PROGRESS.evalNs],
        validNs: [...DEFAULT_LAST_N_PROGRESS.validNs],
        disableNs: [...DEFAULT_LAST_N_PROGRESS.disableNs],
      },
      intervalStrategy: { ...DEFAULT_INTERVAL_STRATEGY },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
      liveTape: true,
      comboOnlyPositive: true,
      comboTactic: "all",
      comboRange: "all",
      evalHours: [4, 8, 16, 20],
      evalLastNs: [50, 15, 12],
      lastN: 15,
      lastNs: { picks: 15, lanes: 15, last: 15, ongoing: 15, next: 15, combos: 15 },
      lastNLinked: true,
      hedgeMode: true,
      marginMode: "cross",
      useMaxLeverage: true,
      leverage: 0,
      minSizeRatio: 1,
      sessionPhase: "running",
      strategyToggles: { normal: false, trailing: true, axis: true, block: true, dca: false },
    },
  },
  {
    id: "x01-bots",
    label: "x01 bots",
    blurb: "Mainnet. Sandwich, Clamp, Pivot. Stop 0.4% (cap 0.5%). Trail arms at 0.4% MFE. Volume factor 1. 24h sim: every hour green.",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      sessionPhase: "running",
      bots: x01BotPreset(),
    },
  },
  {
    id: "sl-trail-24",
    label: "SL 0.4 · trail 0.4",
    blurb: "24h×10, 8 bot types, seed 20260922. Stop floor 0.4% of price, never wider than 0.5%. Trail arms once price is 0.4% in favor. All 64 cells stayed hour-green with PF>1. A 0.5% stop raised sandwich drawdown to 14.8%. Trail 0.2% gave back more profit.",
    builtin: true,
    patch: {
      sessionPhase: "running",
      bots: measuredSlTrailBots(),
    },
  },
  {
    id: "tape-6h-8",
    label: "6h × 8 tape",
    blurb: "6h live after 6h pre · 8 symbols · $10 · trailing/atr · short 0.42/1.75 · trail 1.5 · hold 8 · Block 1–6 parallel 0.4/1.5 · PF 1.179 · 220k orders",
    builtin: true,
    patch: {
      symbolCount: 8,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      costStep: 3,
      tacticConfig: {
        trailingPct: 1.5,
        dcaCount: 1,
        dcaDrawdown: 0.8,
        axisSpacing: 0.7,
        axisLevels: 5,
        axisPartialRatio: 3,
        slAtr: 0.735,
        tpRatio: 0.571,
        tpAtr: 0.42,
        slOfTp: 1.75,
        shortRange: true,
        maxHoldBars: 3,
        maxHoldTicks: 8,
      },
      blockConfig: {
        ...DEFAULT_BLOCK_CONFIG,
        enabled: true,
        counts: [1, 2, 3, 4, 5, 6],
        maxMultiple: 6,
        minMultiple: 1,
        volumeRatio: 0.4,
        relVolumeRatio: 0.4,
        sharedVolumeRatio: 1.5,
        overallVolumeRatio: 1.5,
        maxVolumeMultiplier: 8,
        minActiveLevel: 1,
        pauseCountRatio: 0,
        windows: true,
        stack: true,
        volumeMode: "parallel",
        overallMode: "parallel",
        sides: "both",
      },
      pfCoords: { hourKeep: true, bankWin: true, pairAdd: true, laneCool: true, winAgain: true },
      strategyToggles: { normal: false, trailing: true, axis: true, block: true, dca: false },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
    },
    info: {
      winHoursPct: 1,
      pf: 1.179,
      ddt: 356,
      tradesPerHour: 1288,
      positions: 11.48,
      orders: 305.6,
    },
  },
  {
    id: "tape-6h-12",
    label: "6h × 12 stable",
    blurb: "Stable. 6h after 6h pre · 12 symbols · $10 · short 0.48/1 · trail 1.5 · DDT cap 22h · all strategies · Block 0.4/1.5 · PF 1.289 · live 50 symbols · vol 1.5",
    builtin: true,
    patch: {
      activeConnId: "bingx-x01",
      symbolCount: 50,
      evalSymbolCount: 300,
      liveSymbolCap: 50,
      tactic: "trailing",
      rangeType: "atr",
      orderType: "limit",
      costStep: 10,
      tacticConfig: {
        trailingPct: 1.5,
        dcaCount: 1,
        dcaDrawdown: 0.8,
        axisSpacing: 0.7,
        axisLevels: 5,
        axisPartialRatio: 3,
        slAtr: 0.48,
        tpRatio: 1,
        tpAtr: 0.48,
        slOfTp: 1,
        shortRange: true,
        maxHoldBars: 3,
        maxHoldTicks: 8,
      },
      blockConfig: {
        ...DEFAULT_BLOCK_CONFIG,
        enabled: true,
        counts: [1, 3, 4, 5, 6],
        maxMultiple: 6,
        minMultiple: 1,
        volumeRatio: 0.4,
        relVolumeRatio: 0.4,
        sharedVolumeRatio: 1.5,
        overallVolumeRatio: 1.5,
        maxVolumeMultiplier: 8,
        minActiveLevel: 1,
        pauseCountRatio: 0,
        windows: true,
        stack: true,
        volumeMode: "parallel",
        overallMode: "parallel",
        sides: "both",
        overall: true,
      },
      thresholds: { ...DEFAULT_THRESHOLDS, maxDdt: 22 },
      pfCoords: { hourKeep: true, bankWin: true, pairAdd: true, laneCool: true, winAgain: true },
      strategyToggles: { normal: true, trailing: true, axis: true, block: true, dca: true },
      enabledKinds: [...DEFAULT_ENABLED_KINDS],
      minSizeRatio: 1.5,
      liveTape: true,
      sessionPhase: "running",
    },
    info: {
      winHoursPct: 1,
      pf: 1.289,
      ddt: 84,
      tradesPerHour: 824,
      positions: 147.3,
      orders: 105.4,
    },
  },
];

export function measuredSlTrailBots() {
  const bots = defaultBotsPersist();
  bots.hours = 24;
  bots.armed = ["sandwich", "clamp", "pivot"];
  bots.selected = "sandwich";
  for (const t of BOT_TYPES) {
    bots.configs[t] = { ...defaultBotConfig(t), minSl: 0.4, minTrail: 0.4, hours: 24 };
  }
  return bots;
}

export function x01BotPreset() {
  const bots = defaultBotsPersist();
  bots.selected = "sandwich";
  bots.armed = ["sandwich", "clamp", "pivot"];
  bots.hours = 24;
  for (const t of ["sandwich", "clamp", "pivot"] as const) {
    bots.configs[t] = {
      ...bots.configs[t],
      symbolCount: 10,
      minTp: 0.4,
      minSl: 0.4,
      minTrail: 0.4,
      volumeFactor: 1,
      hours: 24,
      strategies: { normal: false, trailing: true, axis: true, block: true, dca: false },
    };
  }
  bots.configs.sandwich.selectMode = "vol1h";
  bots.configs.clamp.selectMode = "vol1h";
  bots.configs.pivot.selectMode = "range15";
  return bots;
}

export const STABLE_PRESET_ID = "tape-6h-12";

export function sanitizePreset(raw: unknown): SettingsPreset | null {
  if (!raw || typeof raw !== "object") return null;
  const p = raw as Partial<SettingsPreset>;
  const id = typeof p.id === "string" ? p.id.trim().slice(0, 48) : "";
  const label = typeof p.label === "string" ? p.label.trim().slice(0, 40) : "";
  if (!id || !label) return null;
  return {
    id,
    label,
    blurb: typeof p.blurb === "string" ? p.blurb.trim().slice(0, 120) : "Saved preset",
    builtin: false,
    patch: p.patch && typeof p.patch === "object" ? (p.patch as Partial<DeskSettingsSnap>) : {},
  };
}

export function sanitizeUserPresets(raw: unknown): SettingsPreset[] {
  if (!Array.isArray(raw)) return [];
  const out: SettingsPreset[] = [];
  const seen = new Set<string>();
  for (const row of raw) {
    const p = sanitizePreset(row);
    if (!p || p.builtin || seen.has(p.id)) continue;
    seen.add(p.id);
    out.push(p);
    if (out.length >= 24) break;
  }
  return out;
}

export function allPresets(user: SettingsPreset[]): SettingsPreset[] {
  const ids = new Set(BUILTIN_PRESETS.map((p) => p.id));
  return [...BUILTIN_PRESETS, ...user.filter((p) => !ids.has(p.id))];
}

export function findPreset(id: string, user: SettingsPreset[]): SettingsPreset | undefined {
  return allPresets(user).find((p) => p.id === id);
}

export function presetIdOf(label: string) {
  const slug = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 24);
  return `user-${slug || "preset"}-${Date.now().toString(36).slice(-6)}`;
}
